package database

import (
	"context"
	"github.com/jackc/pgx/v5"
	"log"
	"nestnet/internal/database/generated"
)

// Get profile name
func GetName() {
	// Call go code generated by sqlc
}

// Set profile name
func SetName() {
}

// Get public key
func GetPubKey() {
}

// Get private key
func GetPrivKey() {
}

// Get posts
func GetPosts() []generated.Post {
	ctx := context.Background()

	conn, err := pgx.Connect(ctx, "user=nest password=net dbname=nestnetdatabase host=localhost port=5432 sslmode=disable")
	if err != nil {
		log.Fatal(err)
	}
	defer func(conn *pgx.Conn, ctx context.Context) {
		err := conn.Close(ctx)
		if err != nil {
			log.Fatal(err)
		}
	}(conn, ctx)

	queries := generated.New(conn)

	posts, err := queries.GetPosts(ctx)
	if err != nil {
		log.Fatal(err)
	}

	return posts
}
