CREATE TABLE LocalUser (
    id CHAR(36) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    address VARCHAR(255) NOT NULL
);

CREATE TABLE Posts(
    id CHAR(36) PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    body VARCHAR(1024) NOT NULL,
    imgmd5 VARCHAR(16) NOT NULL
);

CREATE TABLE Peers(
    id CHAR(36) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    address VARCHAR(255) NOT NULL
);