version: "3.8"

services:
  nestnet:
    image: nestnet
    ports:
      - 4929:8080
    volumes:
      - nestdata:/var/lib/nestnet/

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"  # Expose the default PostgreSQL port
    volumes:
      - pgdata:/var/lib/postgresql/database  # Persist database with a named volume

volumes:
  pgdata:
  nestdata:

