package data

// Get profile name
func GetName() {
	// Call go code generated by sqlc
}

// Set profile name
func SetName() {
}

// Get public key
func GetPubKey() {
}

// Get private key
func GetPrivKey() {
}

// Get posts
func GetPosts() {
}

func Get