package data

// Get profile name
func getName() {
	// Call go code generated by sqlc
}

// Set profile name
func setName() {
}

// Get public key
func getPubKey() {
}

// Get private key
func getPrivKey() {
}

// Get posts
func getPosts() {
}
